In [1]:
import numpy as np

In [2]:
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

X, y = data[:, :-1], data[:, -1]

#X prints only two rows
# y prints last column as row
print(X)
print(y)

[[1 2]
 [4 5]
 [7 8]]
[3 6 9]


In [6]:
x=data[0:,:]

In [7]:
print(x)  #prints entire array

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
x1=data[2:,:]  #prints 2nd indexed row

In [9]:
print(x1)

[[7 8 9]]


In [10]:
x2=data[:2,:-1] #prints

In [11]:
print(x2)

[[1 2]
 [4 5]]
