In [1]:
import numpy as np

In [5]:
a=np.array([(1,2,3),(1,4,5),(99,6,7)])  #first array creation
print(a)

[[ 1  2  3]
 [ 1  4  5]
 [99  6  7]]


In [7]:
b=np.array([(1,5,6),(8,7,5),(2,3,1)]) #second array creation
print(b)

[[1 5 6]
 [8 7 5]
 [2 3 1]]


In [8]:
#STACKING ARRAYS HORIZONTALLY method 1
np.concatenate([a,b],axis=1)

array([[ 1,  2,  3,  1,  5,  6],
       [ 1,  4,  5,  8,  7,  5],
       [99,  6,  7,  2,  3,  1]])

In [9]:
np.concatenate([a,b],axis=None) #this is giving a linear array

array([ 1,  2,  3,  1,  4,  5, 99,  6,  7,  1,  5,  6,  8,  7,  5,  2,  3,
        1])

In [11]:
#STACKING ARRAYS HORIZONTALLY method 2
np.c_[a,b]             #transltes along second axis hence stacked based on first axis

array([[ 1,  2,  3,  1,  5,  6],
       [ 1,  4,  5,  8,  7,  5],
       [99,  6,  7,  2,  3,  1]])

In [13]:
#STACKING ARRAYS HORIZONTALLY method 2
np.hstack([a,b])     #horizontal stack function

array([[ 1,  2,  3,  1,  5,  6],
       [ 1,  4,  5,  8,  7,  5],
       [99,  6,  7,  2,  3,  1]])