In [1]:
#logspace --> This is similar to geomspace but with endpoints specified indirectly.

import numpy as np

In [2]:
np.logspace(1,10) #default is 50 samples

array([1.00000000e+01, 1.52641797e+01, 2.32995181e+01, 3.55648031e+01,
       5.42867544e+01, 8.28642773e+01, 1.26485522e+02, 1.93069773e+02,
       2.94705170e+02, 4.49843267e+02, 6.86648845e+02, 1.04811313e+03,
       1.59985872e+03, 2.44205309e+03, 3.72759372e+03, 5.68986603e+03,
       8.68511374e+03, 1.32571137e+04, 2.02358965e+04, 3.08884360e+04,
       4.71486636e+04, 7.19685673e+04, 1.09854114e+05, 1.67683294e+05,
       2.55954792e+05, 3.90693994e+05, 5.96362332e+05, 9.10298178e+05,
       1.38949549e+06, 2.12095089e+06, 3.23745754e+06, 4.94171336e+06,
       7.54312006e+06, 1.15139540e+07, 1.75751062e+07, 2.68269580e+07,
       4.09491506e+07, 6.25055193e+07, 9.54095476e+07, 1.45634848e+08,
       2.22299648e+08, 3.39322177e+08, 5.17947468e+08, 7.90604321e+08,
       1.20679264e+09, 1.84206997e+09, 2.81176870e+09, 4.29193426e+09,
       6.55128557e+09, 1.00000000e+10])

In [3]:
np.logspace(1,10,4) #(start,stop,samples) 

#start--> base**start

#stop--> base ** stop

#default base value is 10

array([1.e+01, 1.e+04, 1.e+07, 1.e+10])

In [4]:
np.logspace(1,10,4,base=2)

#start--> 2**1

#stop-->2**10

array([   2.,   16.,  128., 1024.])

In [5]:
np.logspace(1,10,4,base=2,dtype='int') #changing type as int

array([   2,   16,  128, 1024])

In [6]:
np.logspace(1,10,4,base=2,endpoint=False) #end value is not included

array([  2.        ,   9.51365692,  45.254834  , 215.2694823 ])