In [1]:
import numpy as np

In [2]:
np.maximum([12, 13, 14], [1, 5, 2])  #max of size 3 from these arrays

array([12, 13, 14])

In [3]:
np.minimum([2, 3, 4], [1, 5, 2])  #min of size 3 from these arrays

array([1, 3, 2])

In [4]:
np.minimum([12,-1,5,0],[56,67,-3,4]) #min of size 4 from these arrays

array([12, -1, -3,  0])

In [5]:
np.maximum(np.eye(2), [0.5, 2]) #max of eye(2) and the specified array --> broadcasting

array([[1. , 2. ],
       [0.5, 2. ]])

In [6]:
np.minimum(np.identity(3),[4,0,-1]) #min of identity matrix and an array --> broadcasting

array([[ 1.,  0., -1.],
       [ 0.,  0., -1.],
       [ 0.,  0., -1.]])