In [6]:
import numpy as np
m = np.ones((3,3))       #create 3*3 matrix of ones

m1 = np.pad(m, pad_width=1, mode='constant', constant_values=0) #pad with 0's all side
print(m1)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
np.pad(m,pad_width=2,mode='constant',constant_values=2) #pad 2 rows of 2 all side

array([[2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 1., 1., 1., 2., 2.],
       [2., 2., 1., 1., 1., 2., 2.],
       [2., 2., 1., 1., 1., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2.]])

In [8]:
np.pad(m,pad_width=1,mode='edge')     #pads with edge values of array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
a=[1,2,3,4,5,6]
print(a)

[1, 2, 3, 4, 5, 6]


In [11]:
np.pad(a,pad_width=1,mode='edge') #only edges are padded

array([1, 1, 2, 3, 4, 5, 6, 6])

In [12]:
np.pad(a,pad_width=1,mode='maximum') #pads with maximum values

array([6, 1, 2, 3, 4, 5, 6, 6])

In [13]:
np.pad(a,pad_width=1,mode='minimum') #pads with minimum values

array([1, 1, 2, 3, 4, 5, 6, 1])