In [7]:
import numpy as np
from io import BytesIO
from PIL import Image   #importing python image library
import PIL, requests

# Import image from URL
URL = 'https://images3.alphacoders.com/823/82317.jpg'
response = requests.get(URL)  #retrieving image from requests

# Read it as Image
I = Image.open(BytesIO(response.content))  #opening the image

I=I.resize([3,3])

# Convert to numpy array
arr = np.asarray(I)  
print(arr)

# Optionaly Convert it back to an image and show
#im = PIL.Image.fromarray(np.uint8(arr))
#Image.Image.show(im)

[[[ 49 100 191]
  [ 11  33  80]
  [ 16  46 106]]

 [[ 60 152 147]
  [  8  15   8]
  [  9   4   1]]

 [[ 41  70  39]
  [ 90  63  52]
  [ 69 156  88]]]
