In [7]:
import numpy as np

In [10]:
a=np.arange(2,11) #array creation 

In [11]:
print(a) #seems to be linear

[ 2  3  4  5  6  7  8  9 10]


In [13]:
a=a.reshape(3,3) #reshaping to #*3

In [14]:
print(a)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [16]:
#REVERSING ROWS
print(a[::-1])

[[ 8  9 10]
 [ 5  6  7]
 [ 2  3  4]]


In [18]:
#REVERSING COLUMNS
print(a[:,::-1])

[[ 4  3  2]
 [ 7  6  5]
 [10  9  8]]
