In [1]:
import numpy as np

In [2]:
x=np.arange(1,10,2) #creation of an array

In [3]:
print(x)

[1 3 5 7 9]


In [5]:
print(np.degrees(x)) #degrees of the array

[ 57.29577951 171.88733854 286.47889757 401.07045659 515.66201562]


In [6]:
print(np.radians(x)) #radians of the array

[0.01745329 0.05235988 0.08726646 0.12217305 0.15707963]


In [9]:
x1=np.ones((3,3))

In [10]:
print(x1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
print(np.radians(x1))

[[0.01745329 0.01745329 0.01745329]
 [0.01745329 0.01745329 0.01745329]
 [0.01745329 0.01745329 0.01745329]]


In [12]:
print(np.degrees(x1))

[[57.29577951 57.29577951 57.29577951]
 [57.29577951 57.29577951 57.29577951]
 [57.29577951 57.29577951 57.29577951]]
