In [1]:
import numpy as np

In [2]:
print(np.rad2deg(18)) #radian to degree conversion

1031.324031235482


In [3]:
print(np.deg2rad(180)) #degree to radian conversion

3.141592653589793


In [4]:
np.around([0.67,5.67,3.34]) #rounding off an array

array([1., 6., 3.])

In [7]:
np.around([9.92,9.99,8.85],decimals=1) #rounding off with one decimal point

array([ 9.9, 10. ,  8.8])

In [8]:
np.around([6.76,5.54],decimals=-1) #rounding off with no decimal point

array([10., 10.])

In [9]:
np.round(9.98) #rounding off a number

10.0

In [13]:
np.round(9.412)

10.0

In [14]:
np.round(8.23)

8.0