In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])

In [3]:
print(a)

[1 2 3 4]


In [4]:
np.repeat(a,4) #repeats array 4 times

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])

In [5]:
np.repeat(a,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [12]:
np.repeat(a,5,axis=0)  #t axis 0

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4])

In [13]:
np.repeat(3,4)  #repeats 3 4times

array([3, 3, 3, 3])