In [16]:
import numpy as np

x = np.arange(1,10,2)
np.savetxt('test.out', x, delimiter=',') #saving to test.out


In [17]:
y=np.loadtxt('test.out') #loading test.out
print(y)

[1. 3. 5. 7. 9.]


In [18]:
arr=np.array([[1,2],[3,4]]) #array creation

In [19]:
np.savetxt('test1.out',arr) #saving to test1.out

In [20]:
np.loadtxt('test1.out')  #loading to test1.out

array([[1., 2.],
       [3., 4.]])

In [22]:
x1=np.identity(3) #creates an identity matrix

In [23]:
np.savetxt('try.txt',x1) #saving in a txt file

In [24]:
np.loadtxt('try.txt') #loading text file

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.save('num.npy',x1) #storing in binary file

In [27]:
np.load('num.npy') #load for binary file

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])