In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [3]:
print(a)

[1 2 3 2 3 4 3 4 5 6]


In [4]:
print(b)

[ 7  2 10  2  7  4  9  4  9  8]


In [8]:
np.union1d(a,b) #union of 2 arrays

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.intersect1d(a,b) #common elements between 2 arrays

array([2, 4])

In [7]:
np.setdiff1d(a,b) #set difference of 2 arrays

array([1, 3, 5, 6])