In [1]:
import numpy as np

In [3]:
data = np.array([10, 20, 30, 40, 50])

In [5]:
print(data[:])  #prints entire array

[10 20 30 40 50]


In [6]:
print(data[0:3]) #prints indices from 0 and 3

[10 20 30]


In [7]:
print(data[:2]) # prints elements before 2nd index

[10 20]


In [8]:
print(data[3:]) # prints elements after 3rd index

[40 50]


In [13]:
print(data[::-1]) #prints the reversed array

[50 40 30 20 10]
