In [1]:
#STACKING ARRAYS VERTICALLY
import numpy as np

In [6]:
a1=np.array([(2,3,4),(9,8,7)]) #no problem with 2d array
print(a1)

[[2 3 4]
 [9 8 7]]


In [7]:
a2=np.arange(10) # 1D array is always linearly printed
print(a2)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
a = np.arange(10).reshape(2,-1)  #being reshaped vertically
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [5]:
b = np.repeat(1, 10).reshape(2,-1)  #array of repeating 1 10 times is stacked vertically 
print(b)

[[1 1 1 1 1]
 [1 1 1 1 1]]
