In [1]:
import numpy as np

In [3]:
#Construct an array by repeating A the number of times given by reps.
a=np.array([0,1,6,7])


In [4]:
np.tile(a,3)  #repeating array values 3 times

array([0, 1, 6, 7, 0, 1, 6, 7, 0, 1, 6, 7])

In [5]:
np.tile(a,(2,1))    #The number of repetitions of A along each axis.

array([[0, 1, 6, 7],
       [0, 1, 6, 7]])

In [8]:
np.tile(a,(2,2))  #repeating 2 times by x axis and y axis

array([[0, 1, 6, 7, 0, 1, 6, 7],
       [0, 1, 6, 7, 0, 1, 6, 7]])

In [9]:
np.tile(a,(2,1,2)) #a shape (3,) array is promoted to (1, 3) for 2-D replication, or shape (1, 1, 3) for 3-D replication.

array([[[0, 1, 6, 7, 0, 1, 6, 7]],

       [[0, 1, 6, 7, 0, 1, 6, 7]]])

In [10]:
np.tile(a,(2,1,3)) #repeating 3 times with axis 2 and 1

array([[[0, 1, 6, 7, 0, 1, 6, 7, 0, 1, 6, 7]],

       [[0, 1, 6, 7, 0, 1, 6, 7, 0, 1, 6, 7]]])