In [1]:
#STACKING ARRAYS VERTICALLY
import numpy as np

In [6]:
a1=np.array([(2,3,4),(9,8,7)]) #no problem with 2d array
print(a1)

[[2 3 4]
 [9 8 7]]


In [7]:
a2=np.arange(10) # 1D array is always linearly printed
print(a2)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
a = np.arange(10).reshape(2,-1)  #being reshaped vertically
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [10]:
b = np.repeat(1, 10).reshape(2,-1)  #array of repeating 1 10 times is stacked vertically 
print(b)

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [19]:
# Method 1 to stack vertically:
np.concatenate([a, b], axis=0)  #concatenate 2 arrays  [axis--> The axis along which the arrays will be joined.]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
# Method 2 to stack vertically:
np.vstack([a, b])               #np.vstack --> Stack arrays in sequence vertically (row wise).

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
# Method 3 to stack vertically:
np.r_[a, b]                         #np.r_ --> Translates slice objects to concatenation along the first axis.

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])